# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'eedcb79e-839a-40ad-b9e5-8106c4903d99'
  imageRepository: 'demos/springboot/rest-soap-service'
  containerRegistry: 'andreandrade.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  jar_path: 'initial/build/libs/rest-soap-service-0.1.0.jar'
  aci_name: restsoapservice
  aci_rg: raizen_apim_translate_demo

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: CI
  displayName: Build and push stage (CI)
  jobs:
  - job: CI
    displayName: Build and Push image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Gradle@3
      inputs:
        gradleWrapperFile: '$(Build.SourcesDirectory)/initial/gradlew'
        workingDirectory: '$(Build.SourcesDirectory)/initial'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
    
    - task: Docker@2
      inputs:
        containerRegistry: 'andreandrade'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '--build-arg JAR_FILE=$(jar_path) -t $(containerRegistry)/$(imageRepository):$(tag) -t $(containerRegistry)/$(imageRepository):latest'
        
    - task: Docker@2
      inputs:
        containerRegistry: 'andreandrade'
        repository: '$(imageRepository)'
        command: 'push'
        tags: |
          latest
          $(tag)

- stage: CD
  displayName: Deploying container (CD)
  dependsOn: CI
  condition: succeeded('CI')
  jobs:
  - job: CD
    displayName: Build and Push image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'andreandrade_internal(29eb732c-7f74-4314-82af-336bfd45139d)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container restart --name $(aci_name)  --resource-group $(aci_rg)'
