# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.2
      with:
        arguments: build
        gradle-executable: initial/gradlew
        build-root-directory: initial
        
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_SP }}
        password: ${{ secrets.ACR_SP_PWD }}
        login-server: ${{ secrets.ACR_URL }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: ${{ github.workspace }}
        build-args: JAR_FILE=initial/build/libs/rest-soap-service-0.1.0.jar
        push: true
        tags: |
          ${{ secrets.ACR_URL }}/demos/springboot/rest-soap-service:latest
          
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        inlineScript: az container restart --name ${{ secrets.ACI_NAME }}  --resource-group ${{ secrets.ACI_RG }}
